react queryによるAPI呼び出しの共通化ヘルパーを作成
mabell-makeup/frontend pull request #16
Opened 2022-05-16 18:20 UTC by srtxx

### JIRA

https://mabell.atlassian.net/browse/MBL-4

### 概要

react queryによる呼び出しの共通化ヘルパーを作成
apiリクエストの疎通まで確認

### 対応スレ

リクエストヘルパーの作成

### 関連リンク

### その他

2022-05-19 05:23 UTC, srtxx commented on src/App.tsx
> +const myDiv = styled.div`
なるほど、コンポーネントだったんだ....:bow:
修正します！

2022-05-24 11:29 UTC, daiti0113 requested changes
すまんーー、1箇所見落としてた！

2022-05-24 11:29 UTC, daiti0113 commented on package.json
> +    "axios": "^0.27.2",
すまん！！1回目のレビューで気づかなかった！
axios使ってないかも！！
削除して、再度 `npm i` してほしいです！

2022-05-24 12:21 UTC, daiti0113 approved these changes
LGTM

2022-05-24 12:21 UTC, merged